# Generated by Django 2.1.2 on 2018-11-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('middleName', models.CharField(blank=True, max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonTicketHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField()),
                ('customer', models.ManyToManyField(to='webapp.Customer')),
                ('seasons', models.ManyToManyField(to='webapp.Season')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('handicapped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pricegroups', models.ManyToManyField(to='webapp.PriceGroup')),
                ('rows', models.ManyToManyField(to='webapp.Row')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=500)),
                ('group', models.ManyToManyField(to='auth.Group')),
                ('performances', models.ManyToManyField(to='webapp.Performance')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('sections', models.ManyToManyField(to='webapp.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('datePurchased', models.DateTimeField(verbose_name='Date Purchased')),
                ('door', models.BooleanField()),
                ('printed', models.BooleanField(default=False)),
                ('cash', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer', models.ManyToManyField(to='webapp.Customer')),
                ('performance', models.ManyToManyField(to='webapp.Performance')),
                ('row', models.ManyToManyField(to='webapp.Row')),
                ('season', models.ManyToManyField(to='webapp.Season')),
                ('seat', models.ManyToManyField(to='webapp.Seat')),
                ('section', models.ManyToManyField(to='webapp.Section')),
                ('show', models.ManyToManyField(to='webapp.Show')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='shows',
            field=models.ManyToManyField(to='webapp.Show'),
        ),
        migrations.AddField(
            model_name='row',
            name='seats',
            field=models.ManyToManyField(to='webapp.Seat'),
        ),
        migrations.AddField(
            model_name='performance',
            name='theater',
            field=models.ManyToManyField(to='webapp.Theater'),
        ),
    ]
