# Generated by Django 2.1 on 2018-11-17 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonTicketHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='genre',
            field=models.CharField(default=datetime.datetime(2018, 11, 17, 21, 49, 44, 626438), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='show',
            name='img',
            field=models.CharField(default=datetime.datetime(2018, 11, 17, 21, 50, 31, 701231), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='runtime',
            field=models.CharField(default='4 hrs., 20 mins.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='summary',
            field=models.CharField(default='This is my summary', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='row',
            field=models.ManyToManyField(to='webapp.Row'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='section',
            field=models.ManyToManyField(to='webapp.Section'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='seasonticketholder',
            name='customer',
            field=models.ManyToManyField(to='webapp.Customer'),
        ),
        migrations.AddField(
            model_name='seasonticketholder',
            name='seasons',
            field=models.ManyToManyField(to='webapp.Season'),
        ),
    ]
